name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: jakejarvis/hugo-build-action@v0.57.2
      name: Rebuild
      with:
        args: --minify -s doc-src/
    - uses: matheusalbino/git-commit@v1.0.0
      name: Commit updates
      with:
        user-name: Mitchell Admin (from Github Actions)
        user-email: itpp-bot@it-projects.info
        message: |
          :alien: recompile docs
          
          Sent from Github Actions (see .github/workflows/main.yml )
        github-token: ${{ secrets.GITHUB_TOKEN }}
